language:
  - node_js

node_js:
  - 12

env:
  - DATABASE_URL=postgresql://postgres@localhost:5432/waiter-availability

before_script:
  - psql -c 'create database waiter-availability;' -U postgres
  - psql -U postgres -d waiter-availability -a -f database.sql

services:
  - postgresql